<?php

namespace SoftUniBlogBundle\Repository;

/**
 * PageSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
